"""Code-defined scenario catalog: support boundaries and defaults."""
from __future__ import annotations

from typing import Dict, FrozenSet, Optional

from .scenario_schema import (
    DRAFT_ONLY,
    SUPPORTED_APPROVAL,
    SUPPORTED_AUTO,
    UNSUPPORTED,
    ScenarioContract,
)

SCENARIO_CATALOG: Dict[str, ScenarioContract] = {
    "repoHelpVerified": ScenarioContract(
        scenario_id="repoHelpVerified",
        category="delegated_repo",
        support_level=SUPPORTED_AUTO,
        action_class="repo_change",
        default_plan_kind="delegated_repo_task",
        required_capabilities=("plan_runtime", "execution_runtime", "verification"),
        allowed_lanes=("openclaw_hybrid", "cursor"),
        default_risk_tier=2,
        approval_mode="auto",
        verification_class="repo_checks",
        receipt_mode="proof_first",
        memory_policy="read_only",
        persona_mode="repo_trust",
        blocks_auto_delegate=False,
        user_facing_label="Repo help (verified)",
    ),
    "statusFollowupContinue": ScenarioContract(
        scenario_id="statusFollowupContinue",
        category="continuity",
        support_level=SUPPORTED_AUTO,
        action_class="status_read",
        default_plan_kind="direct_status",
        required_capabilities=("goal_runtime", "execution_projection"),
        allowed_lanes=("direct_assistant", "openclaw_hybrid", "cursor"),
        default_risk_tier=0,
        approval_mode="auto",
        verification_class="none",
        receipt_mode="standard",
        memory_policy="read_only",
        persona_mode="calm_status",
        blocks_auto_delegate=False,
        user_facing_label="Status or follow-up",
    ),
    "noteOrReminderCapture": ScenarioContract(
        scenario_id="noteOrReminderCapture",
        category="memory",
        support_level=SUPPORTED_AUTO,
        action_class="memory_write",
        default_plan_kind="memory_capture",
        required_capabilities=("memory_engine", "reminders"),
        allowed_lanes=("direct_assistant", "openclaw_hybrid"),
        default_risk_tier=1,
        approval_mode="auto",
        verification_class="none",
        receipt_mode="standard",
        memory_policy="capture_ok",
        persona_mode="capture_receipt",
        blocks_auto_delegate=False,
        user_facing_label="Notes or reminders",
    ),
    "recentMessagesOrInboxLookup": ScenarioContract(
        scenario_id="recentMessagesOrInboxLookup",
        category="messaging_read",
        support_level=SUPPORTED_AUTO,
        action_class="structured_lookup",
        default_plan_kind="direct_lookup",
        required_capabilities=("capability_truth", "structured_lookup"),
        allowed_lanes=("direct_assistant", "openclaw_hybrid"),
        default_risk_tier=1,
        approval_mode="auto",
        verification_class="none",
        receipt_mode="standard",
        memory_policy="read_only",
        persona_mode="lookup_truth",
        blocks_auto_delegate=False,
        user_facing_label="Recent messages / inbox",
    ),
    "approvalRequiredOutboundAction": ScenarioContract(
        scenario_id="approvalRequiredOutboundAction",
        category="external_write",
        support_level=DRAFT_ONLY,
        action_class="outbound_send",
        default_plan_kind="approval_gated_outbound",
        required_capabilities=("plan_runtime", "approval", "external_adapter"),
        allowed_lanes=tuple(),
        default_risk_tier=3,
        approval_mode="required",
        verification_class="provider_receipt",
        receipt_mode="blocked_summary",
        memory_policy="read_only",
        persona_mode="approval_outbound",
        blocks_auto_delegate=True,
        user_facing_label="Outbound action (approval required)",
    ),
    "verificationSensitiveAction": ScenarioContract(
        scenario_id="verificationSensitiveAction",
        category="proof_bound",
        support_level=SUPPORTED_APPROVAL,
        action_class="proof_bound_work",
        default_plan_kind="delegated_repo_task",
        required_capabilities=("verification", "plan_runtime"),
        allowed_lanes=("openclaw_hybrid", "cursor"),
        default_risk_tier=3,
        approval_mode="required",
        verification_class="human_confirm",
        receipt_mode="proof_first",
        memory_policy="read_only",
        persona_mode="proof_bound",
        blocks_auto_delegate=False,
        user_facing_label="Verification-sensitive work",
    ),
    "goalContinuationAcrossSessions": ScenarioContract(
        scenario_id="goalContinuationAcrossSessions",
        category="continuity",
        support_level=SUPPORTED_AUTO,
        action_class="resume_goal",
        default_plan_kind="goal_resume",
        required_capabilities=("goals", "attempts", "plans"),
        allowed_lanes=("direct_assistant", "openclaw_hybrid", "cursor"),
        default_risk_tier=1,
        approval_mode="auto",
        verification_class="none",
        receipt_mode="standard",
        memory_policy="read_only",
        persona_mode="resume",
        blocks_auto_delegate=False,
        user_facing_label="Resume across sessions",
    ),
    "researchSummary": ScenarioContract(
        scenario_id="researchSummary",
        category="research",
        support_level=DRAFT_ONLY,
        action_class="research",
        default_plan_kind="research",
        required_capabilities=("search", "synthesis"),
        allowed_lanes=("direct_assistant", "openclaw_hybrid"),
        default_risk_tier=1,
        approval_mode="auto",
        verification_class="citation",
        receipt_mode="proof_first",
        memory_policy="read_only",
        persona_mode="research",
        blocks_auto_delegate=False,
        user_facing_label="Fresh research / web summary",
    ),
    "multiStepTroubleshoot": ScenarioContract(
        scenario_id="multiStepTroubleshoot",
        category="diagnostics",
        support_level=DRAFT_ONLY,
        action_class="troubleshoot",
        default_plan_kind="multi_step",
        required_capabilities=("plans", "evidence"),
        allowed_lanes=("openclaw_hybrid", "cursor", "direct_assistant"),
        default_risk_tier=2,
        approval_mode="auto",
        verification_class="repo_checks",
        receipt_mode="standard",
        memory_policy="read_only",
        persona_mode="troubleshoot",
        blocks_auto_delegate=False,
        user_facing_label="Multi-step troubleshooting",
    ),
    "mixedResourceGoal": ScenarioContract(
        scenario_id="mixedResourceGoal",
        category="mixed",
        support_level=DRAFT_ONLY,
        action_class="mixed_lane",
        default_plan_kind="mixed",
        required_capabilities=("router", "plan_runtime"),
        allowed_lanes=("openclaw_hybrid", "cursor", "direct_assistant"),
        default_risk_tier=2,
        approval_mode="auto",
        verification_class="repo_checks",
        receipt_mode="standard",
        memory_policy="default",
        persona_mode="mixed",
        blocks_auto_delegate=False,
        user_facing_label="Mixed direct + delegated work",
    ),
    "unsupportedOrUnsafeRequest": ScenarioContract(
        scenario_id="unsupportedOrUnsafeRequest",
        category="safety",
        support_level=UNSUPPORTED,
        action_class="blocked",
        default_plan_kind="none",
        required_capabilities=tuple(),
        allowed_lanes=tuple(),
        default_risk_tier=4,
        approval_mode="required",
        verification_class="none",
        receipt_mode="blocked_summary",
        memory_policy="read_only",
        persona_mode="refusal",
        blocks_auto_delegate=True,
        user_facing_label="Unsupported or unsafe",
    ),
}

# First supported scenario pack (product boundary): keep others draft/unsupported in catalog.
FIRST_SUPPORTED_SCENARIO_IDS: FrozenSet[str] = frozenset(
    {
        "repoHelpVerified",
        "verificationSensitiveAction",
        "multiStepTroubleshoot",
        "statusFollowupContinue",
        "noteOrReminderCapture",
        "recentMessagesOrInboxLookup",
    }
)


def get_contract(scenario_id: str) -> Optional[ScenarioContract]:
    return SCENARIO_CATALOG.get(str(scenario_id or "").strip())


def default_contract() -> ScenarioContract:
    return SCENARIO_CATALOG["mixedResourceGoal"]
