#!/usr/bin/env bash
# Interactive setup: Cursor API env, optional OpenClaw skill install, quick verify.
# Run from anywhere:  bash scripts/setup_admin.sh
set -euo pipefail

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${BASE_DIR}/.env"
SKILL_SRC="${BASE_DIR}/skills/cursor_handoff"
SKILL_DEST="${HOME}/.openclaw/workspace/skills/cursor_handoff"
CLI="${BASE_DIR}/scripts/cursor_openclaw.py"

say() { printf '%s\n' "$*"; }

die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

require_bash() {
  if [ -z "${BASH_VERSION:-}" ]; then
    die "Run with bash: bash scripts/setup_admin.sh"
  fi
}

write_env_file() {
  local api_key="$1" base_url="$2" auth_mode="$3" email="$4" default_mode="$5" target="$6"
  umask 077
  export _ENV_W_TARGET="$target"
  export _ENV_W_API_KEY="$api_key"
  export _ENV_W_BASE="$base_url"
  export _ENV_W_AUTH="$auth_mode"
  export _ENV_W_EMAIL="$email"
  export _ENV_W_MODE="$default_mode"
  python3 - <<'PY'
import json
import os
from pathlib import Path


def line(key: str, value: str) -> str:
    return f"{key}={json.dumps(value)}\n"


path = Path(os.environ["_ENV_W_TARGET"])
chunks = [
    "# Generated by scripts/setup_admin.sh — do not commit (see .gitignore).",
    "# Values are JSON strings so Python CLIs can load this file without `source`.",
    "# Shell:  set -a && source .env && set +a  (still supported)",
    "",
    line("CURSOR_API_KEY", os.environ.get("_ENV_W_API_KEY", "")),
    line("CURSOR_BASE_URL", os.environ.get("_ENV_W_BASE", "https://api.cursor.com")),
    line("CURSOR_AUTH_MODE", os.environ.get("_ENV_W_AUTH", "auto")),
    line("CURSOR_EMAIL", os.environ.get("_ENV_W_EMAIL", "")),
    "",
    "# cursor_handoff skill (OPENCLAW_CURSOR_DEFAULT_MODE)",
    line("OPENCLAW_CURSOR_DEFAULT_MODE", os.environ.get("_ENV_W_MODE", "auto")),
    "",
    "# Optional: macOS SSL — set path to CA bundle if needed, e.g. from python certifi",
    "",
]
path.write_text("\n".join(chunks) + "\n", encoding="utf-8")
PY
  unset _ENV_W_TARGET _ENV_W_API_KEY _ENV_W_BASE _ENV_W_AUTH _ENV_W_EMAIL _ENV_W_MODE
  chmod 600 "$target" || true
}

sync_skill_tree() {
  mkdir -p "${HOME}/.openclaw/workspace/skills"
  rm -rf "$SKILL_DEST"
  cp -R "$SKILL_SRC" "$SKILL_DEST"
  say "Skill copied to: $SKILL_DEST"
}

run_batch() {
  local api_key="$1" base_url="$2" auth_mode="$3" email="$4" default_mode="$5"
  write_env_file "$api_key" "$base_url" "$auth_mode" "$email" "$default_mode" "$ENV_FILE"
  say "Wrote $ENV_FILE (mode 600)."
  [ -d "$SKILL_SRC" ] || die "Missing skill source: $SKILL_SRC"
  sync_skill_tree
  write_env_file "$api_key" "$base_url" "$auth_mode" "$email" "$default_mode" "$SKILL_DEST/.env"
  say "Wrote $SKILL_DEST/.env (mode 600)."
  if command -v openclaw >/dev/null 2>&1; then
    openclaw gateway restart
    say "Gateway restarted."
  else
    say "openclaw not in PATH — restart the gateway yourself when ready."
  fi
  if [ -n "${api_key// }" ]; then
    set -a
    # shellcheck source=/dev/null
    source "$ENV_FILE"
    set +a
    python3 "$CLI" --json diagnose || say "diagnose exited non-zero — check key and network."
  else
    say "Skipping diagnose (empty API key)."
  fi
}

main() {
  require_bash
  cd "$BASE_DIR"

  local batch=false force=false
  for arg in "$@"; do
    case "$arg" in
      --batch) batch=true ;;
      --force) force=true ;;
    esac
  done

  if $batch; then
    say ""
    say "=== Cursor + OpenClaw — admin setup (batch) ==="
    say "Repo: $BASE_DIR"
    local api_key="${CURSOR_API_KEY:-}"
    api_key="${api_key//$'\r'/}"
    api_key="${api_key//$'\n'/}"
    if [ -z "${api_key// }" ]; then
      die "Batch mode requires CURSOR_API_KEY in the environment (export it in your terminal, then re-run)."
    fi
    if [ -f "$ENV_FILE" ] && ! $force; then
      die "Refusing to overwrite $ENV_FILE without --force (or remove the file first)."
    fi
    local base_url="${CURSOR_BASE_URL:-https://api.cursor.com}"
    base_url="${base_url%/}"
    local auth_mode="${CURSOR_AUTH_MODE:-auto}"
    case "$auth_mode" in auto|basic|bearer) ;; *) die "CURSOR_AUTH_MODE must be auto, basic, or bearer" ;; esac
    local email="${CURSOR_EMAIL:-}"
    local default_mode="${OPENCLAW_CURSOR_DEFAULT_MODE:-auto}"
    case "$default_mode" in auto|api|cli) ;; *) die "OPENCLAW_CURSOR_DEFAULT_MODE must be auto, api, or cli" ;; esac
    run_batch "$api_key" "$base_url" "$auth_mode" "$email" "$default_mode"
    say ""
    say "=== Done (batch) ==="
    say "CLIs also auto-load ./.env; optional shell: set -a && source .env && set +a"
    say ""
    return 0
  fi

  say ""
  say "=== Cursor + OpenClaw — admin setup ==="
  say "Repo: $BASE_DIR"
  say ""

  if [ -f "$ENV_FILE" ]; then
    read -r -p "Overwrite existing .env? [y/N] " ow
    case "${ow:-}" in y|Y|yes|YES) ;; *) die "Aborted. Remove or rename $ENV_FILE to run again." ;; esac
  fi

  say ""
  say "Cursor User API key (from https://cursor.com/settings ) — input hidden."
  read -r -s -p "CURSOR_API_KEY: " api_key
  say ""
  if [ -z "${api_key// }" ]; then
    say "WARNING: Empty key — you can edit .env later or re-run this script."
  fi

  read -r -p "CURSOR_BASE_URL [https://api.cursor.com]: " base_in
  base_url="${base_in:-https://api.cursor.com}"
  base_url="${base_url%/}"

  read -r -p "CURSOR_AUTH_MODE (auto|basic|bearer) [auto]: " auth_in
  auth_mode="${auth_in:-auto}"
  case "$auth_mode" in auto|basic|bearer) ;; *) die "auth_mode must be auto, basic, or bearer" ;; esac

  read -r -p "CURSOR_EMAIL (optional, legacy/contact): " email

  read -r -p "OPENCLAW_CURSOR_DEFAULT_MODE for skill (auto|api|cli) [auto]: " mode_in
  default_mode="${mode_in:-auto}"
  case "$default_mode" in auto|api|cli) ;; *) die "mode must be auto, api, or cli" ;; esac

  write_env_file "$api_key" "$base_url" "$auth_mode" "$email" "$default_mode" "$ENV_FILE"
  say "Wrote $ENV_FILE (mode 600)."

  say ""
  say "OpenClaw skill: copies repo skills/cursor_handoff → ~/.openclaw/workspace/skills/cursor_handoff"
  say "(replaces that folder if it already exists)."
  read -r -p "Install / refresh cursor_handoff in OpenClaw workspace? [Y/n] " sk
  case "${sk:-y}" in n|N|no|NO) ;; *)
    [ -d "$SKILL_SRC" ] || die "Missing skill source: $SKILL_SRC"
    sync_skill_tree
    write_env_file "$api_key" "$base_url" "$auth_mode" "$email" "$default_mode" "$SKILL_DEST/.env"
    say "Wrote $SKILL_DEST/.env (mode 600)."
    ;;
  esac

  say ""
  read -r -p "Restart OpenClaw gateway (openclaw gateway restart)? [Y/n] " gw
  case "${gw:-y}" in n|N|no|NO) ;; *)
    if command -v openclaw >/dev/null 2>&1; then
      openclaw gateway restart
      say "Gateway restarted."
    else
      say "openclaw not in PATH — restart the gateway yourself when ready."
    fi
    ;;
  esac

  say ""
  read -r -p "Run API diagnose with this .env (needs network)? [Y/n] " diag
  case "${diag:-y}" in n|N|no|NO) ;; *)
    if [ -z "${api_key// }" ]; then
      say "Skipping diagnose (empty API key)."
    else
      set -a
      # shellcheck source=/dev/null
      source "$ENV_FILE"
      set +a
      python3 "$CLI" --json diagnose || say "diagnose exited non-zero — check key and network."
    fi
    ;;
  esac

  say ""
  say "=== Done ==="
  say "Load credentials in a new shell session:"
  say "  cd \"$BASE_DIR\" && set -a && source .env && set +a"
  say "Then: python3 scripts/cursor_openclaw.py --json whoami"
  say ""
}

main "$@"
