#!/usr/bin/env bash
# Interactive setup: Cursor API env, optional OpenClaw skill install, quick verify.
# Run from anywhere:  bash scripts/setup_admin.sh
set -euo pipefail

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${BASE_DIR}/.env"
SKILL_SRC="${BASE_DIR}/skills/cursor_handoff"
SKILL_DEST="${HOME}/.openclaw/workspace/skills/cursor_handoff"
CLI="${BASE_DIR}/scripts/cursor_openclaw.py"

say() { printf '%s\n' "$*"; }

die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

require_bash() {
  if [ -z "${BASH_VERSION:-}" ]; then
    die "Run with bash: bash scripts/setup_admin.sh"
  fi
}

write_env_file() {
  local api_key="$1" base_url="$2" auth_mode="$3" email="$4" default_mode="$5" target="$6"
  umask 077
  {
    say "# Generated by scripts/setup_admin.sh — do not commit (see .gitignore)."
    say "# Load in your shell:  set -a && source .env && set +a"
    say ""
    printf 'CURSOR_API_KEY=%q\n' "$api_key"
    printf 'CURSOR_BASE_URL=%q\n' "$base_url"
    printf 'CURSOR_AUTH_MODE=%q\n' "$auth_mode"
    printf 'CURSOR_EMAIL=%q\n' "$email"
    say ""
    say "# cursor_handoff skill (used when OPENCLAW_CURSOR_DEFAULT_MODE is set)"
    printf 'OPENCLAW_CURSOR_DEFAULT_MODE=%q\n' "$default_mode"
    say ""
    say "# Optional: if Python hits SSL errors on macOS (uncomment and adjust):"
    say "# SSL_CERT_FILE=\"\$(python3 -c 'import certifi; print(certifi.where())' 2>/dev/null)\""
  } >"$target"
  chmod 600 "$target" || true
}

sync_skill_tree() {
  mkdir -p "${HOME}/.openclaw/workspace/skills"
  rm -rf "$SKILL_DEST"
  cp -R "$SKILL_SRC" "$SKILL_DEST"
  say "Skill copied to: $SKILL_DEST"
}

main() {
  require_bash
  cd "$BASE_DIR"

  say ""
  say "=== Cursor + OpenClaw — admin setup ==="
  say "Repo: $BASE_DIR"
  say ""

  if [ -f "$ENV_FILE" ]; then
    read -r -p "Overwrite existing .env? [y/N] " ow
    case "${ow:-}" in y|Y|yes|YES) ;; *) die "Aborted. Remove or rename $ENV_FILE to run again." ;; esac
  fi

  say ""
  say "Cursor User API key (from https://cursor.com/settings ) — input hidden."
  read -r -s -p "CURSOR_API_KEY: " api_key
  say ""
  if [ -z "${api_key// }" ]; then
    say "WARNING: Empty key — you can edit .env later or re-run this script."
  fi

  read -r -p "CURSOR_BASE_URL [https://api.cursor.com]: " base_in
  base_url="${base_in:-https://api.cursor.com}"
  base_url="${base_url%/}"

  read -r -p "CURSOR_AUTH_MODE (auto|basic|bearer) [auto]: " auth_in
  auth_mode="${auth_in:-auto}"
  case "$auth_mode" in auto|basic|bearer) ;; *) die "auth_mode must be auto, basic, or bearer" ;; esac

  read -r -p "CURSOR_EMAIL (optional, legacy/contact): " email

  read -r -p "OPENCLAW_CURSOR_DEFAULT_MODE for skill (auto|api|cli) [auto]: " mode_in
  default_mode="${mode_in:-auto}"
  case "$default_mode" in auto|api|cli) ;; *) die "mode must be auto, api, or cli" ;; esac

  write_env_file "$api_key" "$base_url" "$auth_mode" "$email" "$default_mode" "$ENV_FILE"
  say "Wrote $ENV_FILE (mode 600)."

  say ""
  say "OpenClaw skill: copies repo skills/cursor_handoff → ~/.openclaw/workspace/skills/cursor_handoff"
  say "(replaces that folder if it already exists)."
  read -r -p "Install / refresh cursor_handoff in OpenClaw workspace? [Y/n] " sk
  case "${sk:-y}" in n|N|no|NO) ;; *)
    [ -d "$SKILL_SRC" ] || die "Missing skill source: $SKILL_SRC"
    sync_skill_tree
    write_env_file "$api_key" "$base_url" "$auth_mode" "$email" "$default_mode" "$SKILL_DEST/.env"
    say "Wrote $SKILL_DEST/.env (mode 600)."
    ;;
  esac

  say ""
  read -r -p "Restart OpenClaw gateway (openclaw gateway restart)? [Y/n] " gw
  case "${gw:-y}" in n|N|no|NO) ;; *)
    if command -v openclaw >/dev/null 2>&1; then
      openclaw gateway restart
      say "Gateway restarted."
    else
      say "openclaw not in PATH — restart the gateway yourself when ready."
    fi
    ;;
  esac

  say ""
  read -r -p "Run API diagnose with this .env (needs network)? [Y/n] " diag
  case "${diag:-y}" in n|N|no|NO) ;; *)
    if [ -z "${api_key// }" ]; then
      say "Skipping diagnose (empty API key)."
    else
      set -a
      # shellcheck source=/dev/null
      source "$ENV_FILE"
      set +a
      python3 "$CLI" --json diagnose || say "diagnose exited non-zero — check key and network."
    fi
    ;;
  esac

  say ""
  say "=== Done ==="
  say "Load credentials in a new shell session:"
  say "  cd \"$BASE_DIR\" && set -a && source .env && set +a"
  say "Then: python3 scripts/cursor_openclaw.py --json whoami"
  say ""
}

main "$@"
